add_library(KosmosEngine STATIC)

target_sources(KosmosEngine
    PRIVATE
        Core/Application.cpp
        Core/Window.cpp
        Core/Input.cpp
        Renderer/Renderer.cpp
        Renderer/Vulkan/VulkanInstance.cpp
        Renderer/Vulkan/VulkanSurface.cpp
        Renderer/Vulkan/VulkanDevice.cpp
        Renderer/Vulkan/VulkanSwapchain.cpp
        Renderer/Vulkan/VulkanGraphicsPipeline.cpp
        Renderer/Vulkan/VulkanFrameContext.cpp
        Renderer/Vulkan/VulkanContext.cpp
        Renderer/Vulkan/VulkanBuffer.cpp
        Renderer/Vulkan/VulkanDescriptorSetLayout.cpp
        Renderer/Vulkan/VulkanDescriptorPool.cpp
        Renderer/Vulkan/VulkanDescriptorWriter.cpp
        Renderer/Vulkan/VulkanDepthBuffer.cpp
        Renderer/Vulkan/VulkanRenderTarget.cpp
        Renderer/Vulkan/VulkanFullscreenPass.cpp
        Renderer/Mesh.cpp
        Renderer/Vulkan/VulkanMesh.cpp
        Renderer/Texture.cpp
        Renderer/Vulkan/VulkanImage.cpp
        Renderer/Vulkan/VulkanTexture.cpp
        Renderer/Material.cpp
        Renderer/Vulkan/VulkanMaterial.cpp
        Renderer/Model.cpp
        Renderer/ObjLoader.cpp
        Scene/Scene.cpp
        Scene/DemoScene.cpp
        Scene/Transform.cpp
        Scene/Camera.cpp
        Scene/CameraController.cpp

    PUBLIC
        Core/Application.h
        Core/Window.h
        Core/Input.h
        Renderer/Vertex.h
        Renderer/CameraUniform.h
        Renderer/Renderer.h
        Renderer/Vulkan/VulkanInstance.h
        Renderer/Vulkan/VulkanSurface.h
        Renderer/Vulkan/VulkanDevice.h
        Renderer/Vulkan/VulkanSwapchain.h
        Renderer/Vulkan/VulkanGraphicsPipeline.h
        Renderer/Vulkan/VulkanGraphicsPipelineDescription.h
        Renderer/Vulkan/VulkanFrameContext.h
        Renderer/Vulkan/VulkanContext.h
        Renderer/Vulkan/VulkanBuffer.h
        Renderer/Vulkan/VulkanDescriptorSetLayout.h
        Renderer/Vulkan/VulkanDescriptorPool.h
        Renderer/Vulkan/VulkanDescriptorWriter.h
        Renderer/Vulkan/VulkanDepthBuffer.h
        Renderer/Vulkan/VulkanRenderTarget.h
        Renderer/Vulkan/VulkanRenderTargetDescription.h
        Renderer/Vulkan/VulkanFullscreenPass.h
        Renderer/ObjectPushConstant.h
        Renderer/Mesh.h
        Renderer/Vulkan/VulkanMesh.h
        Renderer/Texture.h
        Renderer/Vulkan/VulkanImage.h
        Renderer/Vulkan/VulkanTexture.h
        Renderer/Material.h
        Renderer/MaterialUniform.h
        Renderer/Vulkan/VulkanMaterial.h
        Renderer/Model.h
        Renderer/ObjLoader.h
        Renderer/LightingUniform.h
        Scene/Light.h
        Scene/Scene.h
        Scene/DemoScene.h
        Scene/Transform.h
        Scene/Camera.h
        Scene/CameraController.h
)

target_include_directories(KosmosEngine
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}
)

target_link_libraries(KosmosEngine
    PUBLIC
        Vulkan::Vulkan
        glfw
        glm
)

target_compile_definitions(KosmosEngine
    PUBLIC
        GLFW_INCLUDE_VULKAN
        GLM_FORCE_RADIANS
        GLM_FORCE_DEPTH_ZERO_TO_ONE
)